const Links = [
	{
		brand: "Instructure",
		links: [
			{
				title: "Security White Paper",
				from: "/security/dl",
				to: "https://github.com/thedannywahl/instructure-security-package/raw/main/Instructure/Instructure%20Security%20Overview.pdf",
				lang: "EN",
			},
			{
				title: "Business Continuity White Paper",
				from: "/bc/dl",
				to: "https://github.com/thedannywahl/instructure-security-package/raw/main/Instructure/Instructure%20Business%20Continuity%20%26%20Disaster%20Recovery.pdf",
				lang: "EN",
			},
			{
				title: "ISO 27001 Certificate",
				from: "/iso/dl",
				to: "https://github.com/thedannywahl/instructure-security-package/raw/main/Instructure/Instructure%20ISO%2027001%20Compliance%20Certificate.pdf",
				lang: "EN",
			},
			{
				title: "Home",
				from: "/home",
				to: "https://www.instructure.com/?utm_source=INST&utm_medium=ER&CampaignID=7013m000001NyAxAAK",
				lang: "EN",
			},
			{
				title: "Página de inicio",
				from: "/es-la/home",
				to: "https://www.instructure.com/es/?utm_source=INST&utm_medium=ER&CampaignID=7013m000001NyAxAAK",
				lang: "ES_LA",
			},
			{
				title: "Pagina inicial",
				from: "/pt-br/home",
				to: "https://www.instructure.com/pt-br/?utm_source=INST&utm_medium=ER&CampaignID=7013m000001NyAxAAK",
				lang: "PT_BR",
			},
			{
				title: "Startseite",
				from: "/de/home",
				to: "https://www.instructure.com/de?utm_source=INST&utm_medium=ER&CampaignID=7013m000001NyAxAAK",
				lang: "DE",
			},
			{
				title: "Roadmap",
				from: "/roadmap",
				to: "https://community.canvaslms.com/t5/Instructure-Roadmap/ct-p/instructure-roadmap/",
				lang: "EN",
			},
			{
				title: "Accessibility",
				from: "/a11y",
				to: "https://www.instructure.com/accessibility/?utm_source=INST&utm_medium=ER&CampaignID=7013m000001NyAxAAK",
				lang: "EN",
			},
			{
				title: "Contact",
				from: "/contact",
				to: "https://www.instructure.com/contact-us/?utm_source=INST&utm_medium=ER&CampaignID=7013m000001NyAxAAK",
				lang: "EN",
			},
			{
				title: "Contáctenos",
				from: "/es-la/contactenos",
				to: "https://www.instructure.com/es/contactenos/?utm_source=INST&utm_medium=ER&CampaignID=7013m000001NyAxAAK",
				lang: "ES_LA",
			},
			{
				title: "Contato",
				from: "/pt-br/contato",
				to: "https://www.instructure.com/pt-br/contato/?utm_source=INST&utm_medium=ER&CampaignID=7013m000001NyAxAAK",
				lang: "PT_BR",
			},
			{
				title: "Kontakt",
				from: "/kontakt",
				to: "https://www.instructure.com/de/contact-us?utm_source=INST&utm_medium=ER&CampaignID=7013m000001NyAxAAK",
				lang: "DE",
			},
			{
				title: "Privacy",
				from: "/privacy",
				to: "https://www.instructure.com/canvas/privacy/?utm_source=INST&utm_medium=ER&CampaignID=7013m000001NyAxAAK",
				lang: "EN",
			},
			{
				title: "Privacidad",
				from: "/es-la/privicidad",
				to: "https://www.instructure.com/es/canvas/privacidad/?utm_source=INST&utm_medium=ER&CampaignID=7013m000001NyAxAAK",
				lang: "ES_LA",
			},
			{
				title: "Privacidade",
				from: "/pt-br/privacidade",
				to: "https://www.instructure.com/pt-br/canvas/privacidade/?utm_source=INST&utm_medium=ER&CampaignID=7013m000001NyAxAAK",
				lang: "PT_BR",
			},
			{
				title: "Security",
				from: "/security",
				to: "https://www.instructure.com/products/canvas/security/?utm_source=INST&utm_medium=ER&CampaignID=7013m000001NyAxAAK",
				lang: "EN",
			},
			{
				title: "Seguridad",
				from: "/es-la/seguridad",
				to: "https://www.instructure.com/es/canvas/seguridad/?utm_source=INST&utm_medium=ER&CampaignID=7013m000001NyAxAAK",
				lang: "ES_LA",
			},
			{
				title: "Segurança",
				from: "/pt-br/seguranca",
				to: "https://www.instructure.com/pt-br/canvas/seguranca/?utm_source=INST&utm_medium=ER&CampaignID=7013m000001NyAxAAK",
				lang: "PT_BR",
			},
			{
				title: "Trust Center",
				from: "/trust",
				to: "https://www.instructure.com/trust-center/?utm_source=INST&utm_medium=ER&CampaignID=7013m000001NyAxAAK",
				lang: "EN",
			},
			{
				title: "Community",
				from: "/community",
				to: "https://community.canvaslms.com/",
				lang: "EN",
			},
			{
				title: "Terms & Conditions",
				from: "/tos",
				to: "https://www.instructure.com/policies/master-terms-conditions/?utm_source=INST&utm_medium=ER&CampaignID=7013m000001NyAxAAK",
				lang: "EN",
			},
			{
				title: "Global Terms & Conditions",
				from: "/tos/global",
				to: "https://www.instructure.com/policies/global/master-terms-and-conditions/?utm_source=INST&utm_medium=ER&CampaignID=7013m000001NyAxAAK",
				lang: "EN",
			},
			{
				title: "Acceptable Use Policy",
				from: "/aup",
				to: "https://www.instructure.com/policies/acceptable-use/?utm_source=INST&utm_medium=ER&CampaignID=7013m000001NyAxAAK",
				lang: "EN",
			},
			{
				title: "Data Privacy Addendum",
				from: "/dpa",
				to: "https://www.instructure.com/policies/data-processing/?utm_source=INST&utm_medium=ER&CampaignID=7013m000001NyAxAAK",
				lang: "EN",
			},
			{
				title: "Investor Relations",
				from: "/investors",
				to: "https://ir.instructure.com/overview/default.aspx",
				lang: "EN",
			},
			{
				title: "Status",
				from: "/status",
				to: "https://status.instructure.com/",
				lang: "EN",
			},
			{
				title: "CSA Star Registration",
				from: "/csa",
				to: "https://cloudsecurityalliance.org/star/registry/instructure/",
				lang: "EN",
			},
			{
				title: "1EdTech Registrations",
				from: "/1edtech",
				to: "https://site.imsglobal.org/certifications?query=instructure",
				lang: "EN",
			},
			{
				title: "Our Story",
				from: "/story",
				to: "https://www.instructure.com/about/our-story",
				lang: "EN",
			},
			{
				title: "Nuestra Historia",
				from: "/es-la/historia",
				to: "https://www.instructure.com/es/sobre/nuestra-historia",
				lang: "ES_LA",
			},
			{
				title: "Nossa História",
				from: "/pt-br/historia",
				to: "https://www.instructure.com/pt-br/sobre/nossa-historia",
				lang: "PT_BR",
			},
			{
				title: "Try Canvas (FFT)",
				from: "/try-canvas",
				to: "https://www.instructure.com/try-canvas",
				lang: "EN",
			},
			{
				title: "Study Hall",
				from: "/resources",
				to: "https://www.instructure.com/resources/?utm_source=INST&utm_medium=ER&CampaignID=7013m000001NyAxAAK",
				lang: "EN",
			},
			{
				title: "EduAppCenter",
				from: "/apps",
				to: "https://www.eduappcenter.com/",
				lang: "EN",
			},
			{
				title: "ESG Report",
				from: "/esg",
				to: "https://instructure.com/esg-report",
				lang: "EN",
			},
		],
	},
	{
		brand: "Canvas",
		links: [
			{
				title: "Security Audit Report",
				from: "/canvas/audit/dl",
				to: "https://github.com/thedannywahl/instructure-security-package/raw/canvas-lms/Canvas%20LMS/Canvas%20Security%20Audit%20Report.pdf",
				lang: "EN",
			},
			{
				title: "Community",
				from: "/canvas/community",
				to: "https://community.canvaslms.com/t5/Canvas/ct-p/canvas",
				lang: "EN",
			},
			{
				title: "Communidad",
				from: "/es-la/canvas/lms/communidad",
				to: "https://community.canvaslms.com/t5/Recursos-en-Espa%C3%B1ol-Spanish/ct-p/espanol_resources",
				lang: "ES_LA",
			},
			{
				title: "Comunidade",
				from: "/pt-br/canvas/comunidade",
				to: "https://community.canvaslms.com/t5/Recursos-em-Portugu%C3%AAs-Portuguese/ct-p/portuguese_resources",
				lang: "PT_BR",
			},
			{
				title: "Gemeinschaft",
				from: "/de/canvas/gemeinschaft",
				to: "https://community.canvaslms.com/t5/Ressourcen-auf-Deutsch-German/ct-p/german_resources",
				lang: "DE",
			},
			{
				title: "Roadmap",
				from: "/canvas/roadmap",
				to: "https://community.canvaslms.com/t5/Canvas-Product-Roadmap/ct-p/canvas-product-roadmap",
				lang: "EN",
			},
			{
				title: "Ideas",
				from: "/canvas/ideas",
				to: "https://community.canvaslms.com/t5/Canvas-Ideas-and-Themes/ct-p/canvas-ideas-themes?tab=identified",
				lang: "EN",
			},
		],
	},
	{
		brand: "Canvas LMS",
		links: [
			{
				title: "Compliance Package (EN)",
				from: "/canvas/lms/dl",
				to: "https://github.com/thedannywahl/instructure-security-package/archive/refs/heads/canvas-lms.zip",
				lang: "EN",
			},
			{
				title: "Compliance Package (ES-LA)",
				from: "/es-la/canvas/lms/dl",
				to: "https://github.com/thedannywahl/instructure-security-package/archive/canvas-lms-ES_LA.zip",
				lang: "ES_LA",
			},
			{
				title: "Compliance Package (PT-BR)",
				from: "/pt-br/canvas/lms/dl",
				to: "https://github.com/thedannywahl/instructure-security-package/archive/refs/heads/canvas-lms-PT_BR.zip",
				lang: "PT_BR",
			},
			{
				title: "Home (HE)",
				from: "/canvas/lms",
				to: "https://www.instructure.com/higher-education/products/canvas/canvas-lms/?utm_source=INST&utm_medium=ER&CampaignID=7013m000001NyAxAAK",
				lang: "EN",
			},
			{
				title: "Página de inicio (HE)",
				from: "/es-la/canvas/lms",
				to: "https://www.instructure.com/es/canvas/educacion-superior/?utm_source=INST&utm_medium=ER&CampaignID=7013m000001NyAxAAK",
				lang: "ES_LA",
			},
			{
				title: "Página inicial (HE)",
				from: "/canvas/lms/pt",
				to: "https://www.instructure.com/pt-br/canvas/ensino-superior/?utm_source=INST&utm_medium=ER&CampaignID=7013m000001NyAxAAK",
				lang: "PT_BR",
			},
			{
				title: "Startseite",
				from: "/de/canvas/lms",
				to: "https://www.instructure.com/de/hochschule/produkt/canvas/canvas-lms/?utm_source=INST&utm_medium=ER&CampaignID=7013m000001NyAxAAK",
				lang: "DE",
			},
			{
				title: "Home (K12)",
				from: "/canvas/lms/k12",
				to: "https://www.instructure.com/k12/products/canvas/canvas-lms/?utm_source=INST&utm_medium=ER&CampaignID=7013m000001NyAxAAK",
				lang: "EN",
			},
			{
				title: "Página de inicio (K12)",
				from: "/es-la/canvas/lms/basica",
				to: "https://www.instructure.com/es/educacion-basica/?utm_source=INST&utm_medium=ER&CampaignID=7013m000001NyAxAAK",
				lang: "ES_LA",
			},
			{
				title: "Página inicial (K12)",
				from: "/canvas/lms/pt/basica",
				to: "https://www.instructure.com/pt-br/ensino-fundamental-e-medio/?utm_source=INST&utm_medium=ER&CampaignID=7013m000001NyAxAAK",
				lang: "PT_BR",
			},
			{
				title: "VPAT",
				from: "/canvas/lms/vpat",
				to: "https://www.instructure.com/products/canvas/accessibility/?utm_source=INST&utm_medium=ER&CampaignID=7013m000001NyAxAAK",
				lang: "EN",
			},
			{
				title: "Guides",
				from: "/canvas/lms/guides",
				to: "https://community.canvaslms.com/t5/Canvas-Guides/ct-p/canvas_guides/",
				lang: "EN",
			},
			{
				title: "Guías",
				from: "/es-la/canvas/guias",
				to: "https://community.canvaslms.com/t5/Recursos-en-Espa%C3%B1ol-Spanish/ct-p/espanol_resources",
				lang: "ES_LA",
			},
			{
				title: "Guias",
				from: "/pt-br/canvas/guias",
				to: "https://community.canvaslms.com/t5/Recursos-en-Espa%C3%B1ol-Spanish/ct-p/espanol_resources",
				lang: "PT_BR",
			},
			{
				title: "Handbücher",
				from: "/de/canvas/handbuch",
				to: "https://community.canvaslms.com/t5/Ressourcen-auf-Deutsch-German/ct-p/german_resources",
				lang: "DE",
			},
			{
				title: "Release Notes",
				from: "/canvas/lms/releases",
				to: "https://community.canvaslms.com/t5/Canvas-Releases/tkb-p/canvas-release",
				lang: "EN",
			},
			{
				title: "Notas de implementación",
				from: "/es-la/canvas/lms/publicacion",
				to: "https://community.canvaslms.com/t5/Espa%C3%B1ol/tkb-p/canvas-release-espanol",
				lang: "ES_LA",
			},
			{
				title: "Notas de lançamento (Canvas LMS)",
				from: "/canvas/lms/lancamentos",
				to: "https://community.canvaslms.com/t5/Portugues/tkb-p/canvas-release-portugues",
				lang: "PT_BR",
			},
			{
				title: "API",
				from: "/canvas/lms/api",
				to: "https://canvas.instructure.com/doc/api/index.html",
				lang: "EN",
			},
		],
	},
	{
		brand: "Canvas Mobile",
		links: [
			{
				title: "Mobile Apps (Android)",
				from: "/canvas/mobile/android",
				to: "https://play.google.com/store/apps/developer?id=Instructure",
				lang: "EN",
			},
			{
				title: "Mobile Apps (iOS)",
				from: "/canvas/mobile/ios",
				to: "https://apps.apple.com/us/developer/instructure-inc/id418441198",
				lang: "EN",
			},
			{
				title: "Release Notes",
				from: "/canvas/mobile/releases",
				to: "https://community.canvaslms.com/t5/Canvas-Mobile-Releases/tkb-p/CanvasMobileReleases",
				lang: "EN",
			},
			{
				title: "Guides",
				from: "/canvas/mobile/guides",
				to: "https://community.canvaslms.com/t5/Canvas-Mobile-Users/gh-p/mobile",
				lang: "EN",
			},
		],
	},
	{
		brand: "Canvas Studio",
		links: [
			{
				title: "Compliance Package (EN)",
				from: "/canvas/studio/dl",
				to: "https://github.com/thedannywahl/instructure-security-package/archive/refs/heads/canvas-studio.zip",
				lang: "EN",
			},
			{
				title: "Home (HE)",
				from: "/canvas/studio",
				to: "https://www.instructure.com/higher-education/products/canvas/canvas-studio/?utm_source=INST&utm_medium=ER&CampaignID=7013m000001NyAxAAK",
				lang: "EN",
			},
			{
				title: "Home (K12)",
				from: "/canvas/studio/k12",
				to: "https://www.instructure.com/k12/products/canvas/canvas-studio/?utm_source=INST&utm_medium=ER&CampaignID=7013m000001NyAxAAK",
				lang: "EN",
			},
			{
				title: "VPAT",
				from: "/canvas/studio/vpat",
				to: "https://www.instructure.com/accessibility/canvas/canvas-studio-vpat/?utm_source=INST&utm_medium=ER&CampaignID=7013m000001NyAxAAK",
				lang: "EN",
			},
			{
				title: "Guides",
				from: "/canvas/studio/guides",
				to: "https://community.canvaslms.com/t5/Canvas-Studio/ct-p/studio_guides",
				lang: "EN",
			},
			{
				title: "Release Notes",
				from: "/canvas/studio/releases",
				to: "https://community.canvaslms.com/t5/Studio-Releases/ct-p/studio_releases",
				lang: "EN",
			},
			{
				title: "API",
				from: "/canvas/studio/api",
				to: "https://canvas.instructuremedia.com/api/public/docs/#/",
				lang: "EN",
			},
		],
	},
	{
		brand: "Canvas Credentials",
		links: [
			{
				title: "Compliance Package",
				from: "/canvas/credentials/dl",
				to: "https://github.com/thedannywahl/instructure-security-package/archive/refs/heads/canvas-credentials.zip",
				lang: "EN",
			},
			{
				title: "Compliance Package",
				from: "/es-la/canvas/credentials/dl",
				to: "https://github.com/thedannywahl/instructure-security-package/archive/refs/heads/canvas-credentials-ES_LA.zip",
				lang: "ES_LA",
			},
			{
				title: "Compliance Package",
				from: "/pt-br/canvas/credentials/dl",
				to: "https://github.com/thedannywahl/instructure-security-package/archive/refs/heads/canvas-credentials-PT_BR.zip",
				lang: "PT_BR",
			},
			{
				title: "Home (HE)",
				from: "/canvas/credentials",
				to: "https://www.instructure.com/higher-education/products/canvas/canvas-credentials-digital-badges/?utm_source=INST&utm_medium=ER&CampaignID=7013m000001NyAxAAK",
				lang: "EN",
			},
			{
				title: "Home (K12)",
				from: "/canvas/credentials/k12",
				to: "https://www.instructure.com/k12/products/canvas/canvas-credentials-digital-badges/?utm_source=INST&utm_medium=ER&CampaignID=7013m000001NyAxAAK",
				lang: "EN",
			},
			{
				title: "Guides",
				from: "/canvas/credentials/guides",
				to: "https://community.canvaslms.com/t5/Canvas-Credentials-Badges-Badgr/ct-p/canvas-credentials-badges",
				lang: "EN",
			},
			{
				title: "Release Notes",
				from: "/canvas/credentials/releases",
				to: "https://community.canvaslms.com/t5/Badges-Credentials-Releases/tkb-p/badges-release",
				lang: "EN",
			},
			{
				title: "API",
				from: "/canvas/credentials/api",
				to: "https://api.badgr.io/docs/v2/",
				lang: "EN",
			},
		],
	},
	{
		brand: "Canvas Catalog",
		links: [
			{
				title: "Compliance Package",
				from: "/canvas/catalog/dl",
				to: "https://github.com/thedannywahl/instructure-security-package/archive/refs/heads/canvas-catalog.zip",
				lang: "EN",
			},
			{
				title: "Home (HE)",
				from: "/canvas/catalog",
				to: "https://www.instructure.com/higher-education/products/canvas/canvas-catalog/?utm_source=INST&utm_medium=ER&CampaignID=7013m000001NyAxAAK",
				lang: "EN",
			},
			{
				title: "Home (K12)",
				from: "/canvas/catalog/k12",
				to: "https://www.instructure.com/k12/products/canvas/canvas-catalog/?utm_source=INST&utm_medium=ER&CampaignID=7013m000001NyAxAAK",
				lang: "EN",
			},
			{
				title: "Guides",
				from: "/canvas/catalog/guides",
				to: "https://community.canvaslms.com/t5/Canvas-Catalog/ct-p/canvas_catalog",
				lang: "EN",
			},
			{
				title: "Release Notes",
				from: "/canvas/catalog/releases",
				to: "https://community.canvaslms.com/t5/Catalog-Releases/ct-p/catalog_releases",
				lang: "EN",
			},
			{
				title: "API",
				from: "/canvas/catalog/api",
				to: "https://api.catalog.instructure.com/api/docs",
				lang: "EN",
			},
		],
	},
	{
		brand: "Canvas Commons",
		links: [
			{
				title: "Home",
				from: "/canvas/commons",
				to: "https://lor.instructure.com/",
				lang: "EN",
			},
			{
				title: "Guides",
				from: "/canvas/commons/guides",
				to: "https://community.canvaslms.com/t5/Canvas-Commons/tkb-p/commons",
				lang: "EN",
			},
			{
				title: "API",
				from: "/canvas/commons/api",
				to: "https://lor.instructure.com/docs/api/",
				lang: "EN",
			},
		],
	},
	{
		brand: "Canvas Data",
		links: [
			{
				title: "Guides",
				from: "/canvas/data/guides",
				to: "https://community.canvaslms.com/t5/Canvas-Data-Users/gh-p/data",
				lang: "EN",
			},
			{
				title: "API",
				from: "/canvas/data/api",
				to: "https://portal.inshosteddata.com/docs",
				lang: "EN",
			},
		],
	},
	{
		brand: "Mastery",
		links: [
			{
				title: "Community",
				from: "/mastery/community",
				to: "https://community.canvaslms.com/t5/Mastery/ct-p/mastery",
				lang: "EN",
			},
			{
				title: "Roadmap",
				from: "/mastery/roadmap",
				to: "https://community.canvaslms.com/t5/Mastery-Product-Roadmap/ct-p/mastery-product-roadmap",
				lang: "EN",
			},
		],
	},
	{
		brand: "Mastery Connect",
		links: [
			{
				title: "Compliance Package",
				from: "/mastery/connect/dl",
				to: "https://github.com/thedannywahl/instructure-security-package/archive/refs/heads/mastery-connect.zip",
				lang: "EN",
			},
			{
				title: "Home",
				from: "/mastery/connect",
				to: "https://www.instructure.com/k12/products/mastery/mastery-connect",
				lang: "EN",
			},
			{
				title: "Guides",
				from: "/mastery/connect/guides",
				to: "https://community.canvaslms.com/t5/Mastery-Connect/ct-p/masteryconnect",
				lang: "EN",
			},
			{
				title: "Release Notes",
				from: "/mastery/connect/releases",
				to: "https://community.canvaslms.com/t5/Mastery-Connect-Releases/tkb-p/masteryconnect",
				lang: "EN",
			},
			{
				title: "API",
				from: "/mastery/connect/api",
				to: "https://docs.google.com/document/d/19TxyeRzF6nyJDY6ej2dZozbE87JdUygw",
				lang: "EN",
			},
			{
				title: "Mobile App (Android)",
				from: "/mastery/connect/android",
				to: "https://play.google.com/store/apps/dev?id=8869528477632015729&hl=EN&gl=US",
				lang: "EN",
			},
			{
				title: "Mobile App (iOS)",
				from: "/canvas/lms/ios",
				to: "https://apps.apple.com/us/developer/masteryconnect/id413937396",
				lang: "EN",
			},
		],
	},
	{
		brand: "Mastery Item Bank",
		links: [
			{
				title: "Home",
				from: "/mastery/itembank",
				to: "https://www.instructure.com/k12/products/mastery/mastery-item-bank/?utm_source=INST&utm_medium=ER&CampaignID=7013m000001NyAxAAK",
				lang: "EN",
			},
			{
				title: "Guides",
				from: "/mastery/itembank/guides",
				to: "https://community.canvaslms.com/t5/Mastery-Item-Bank/ct-p/mastery-item-bank/?utm_source=INST&utm_medium=ER&CampaignID=7013m000001NyAxAAK",
				lang: "EN",
			},
		],
	},
	{
		brand: "Mastery View Assessments",
		links: [
			{
				title: "Formatives Home",
				from: "mastery/view/formative",
				to: "https://www.instructure.com/k12/products/mastery/mastery-view-formative-assessments/?utm_source=INST&utm_medium=ER&CampaignID=7013m000001NyAxAAK",
				lang: "EN",
			},
			{
				title: "Predictives Home",
				from: "/mastery/view/predictive",
				to: "https://www.instructure.com/k12/products/mastery/mastery-view-predictive-assessments/?utm_source=INST&utm_medium=ER&CampaignID=7013m000001NyAxAAK",
				lang: "EN",
			},
		],
	},
	{
		brand: "Elevate",
		links: [
			{
				title: "Community",
				from: "/elevate/community",
				to: "https://community.canvaslms.com/t5/Elevate/ct-p/elevate",
				lang: "EN",
			},
			{
				title: "Roadmap",
				from: "/elevate/roadmap",
				to: "https://community.canvaslms.com/t5/Elevate-Product-Roadmap/ct-p/elevate-product-roadmap",
				lang: "EN",
			},
		],
	},
	{
		brand: "Elevate K-12 Analytics",
		links: [
			{
				title: "Compliance Package",
				from: "/elevate/k12-analytics/dl",
				to: "https://github.com/thedannywahl/instructure-security-package/archive/refs/heads/elevate-k12-analytics.zip",
				lang: "EN",
			},
			{
				title: "Home",
				from: "/elevate/k12-analytics",
				to: "https://www.instructure.com/k12/products/elevate/elevate-k12-analytics",
				lang: "EN",
			},
			{
				title: "Release Notes",
				from: "/elevate/k12-analytics/releases",
				to: "https://community.canvaslms.com/t5/Elevate-K-12-Analytics-Releases/tkb-p/v_release",
				lang: "EN",
			},
			{
				title: "Guides",
				from: "/elevate/k12analytics/guides",
				to: "https://community.canvaslms.com/t5/Elevate-K-12-Analytics/ct-p/videri",
				lang: "EN",
			},
		],
	},
	{
		brand: "Elevate Standards Alignment",
		links: [
			{
				title: "Compliance Package",
				from: "/elevate/standards-alignment/dl",
				to: "https://github.com/thedannywahl/instructure-security-package/archive/refs/heads/elevate-standards-alignment.zip",
				lang: "EN",
			},
			{
				title: "Home",
				from: "/elevate/standards-alignment",
				to: "https://www.instructure.com/corporate-education/products/elevate/elevate-standards-alignment",
				lang: "EN",
			},
			{
				title: "Release Notes",
				from: "/elevate/standards-alignment/releases",
				to: "https://community.canvaslms.com/t5/Elevate-Standards-Alignment/tkb-p/esa_releases",
				lang: "EN",
			},
			{
				title: "Guides",
				from: "/elevate/standards-alignment/guides",
				to: "https://community.canvaslms.com/t5/Elevate-Standards-Alignment/tkb-p/ab_basics",
				lang: "EN",
			},
		],
	},

	{
		brand: "Elevate Data Quality",
		links: [
			{
				title: "Home",
				from: "/elevate/dataquality",
				to: "https://www.instructure.com/k12/products/elevate/elevate-data-quality/?utm_source=INST&utm_medium=ER&CampaignID=7013m000001NyAxAAK",
				lang: "EN",
			},
			{
				title: "Guides",
				from: "/elevate/dataquality/guides",
				to: "https://community.canvaslms.com/t5/Elevate-Data-Quality/ct-p/certify",
				lang: "EN",
			},
		],
	},
	{
		brand: "Elevate Data Sync",
		links: [
			{
				title: "Guides",
				from: "/elevate/datasync/guides",
				to: "https://community.canvaslms.com/t5/Elevate-Data-Sync/ct-p/elevate_data_sync",
				lang: "EN",
			},
		],
	},
	{
		brand: "Impact",
		links: [
			{
				title: "Compliance Package",
				from: "/impact/dl",
				to: "https://github.com/thedannywahl/instructure-security-package/archive/refs/heads/impact.zip",
				lang: "EN",
			},
			{
				title: "Compliance Package",
				from: "/es-la/impact/dl",
				to: "https://github.com/thedannywahl/instructure-security-package/archive/refs/heads/impact-ES_LA.zip",
				lang: "ES_LA",
			},
			{
				title: "Compliance Package",
				from: "/pt-br/impact/dl",
				to: "https://github.com/thedannywahl/instructure-security-package/archive/refs/heads/impact-PT_BR.zip",
				lang: "PT_BR",
			},
			{
				title: "Home (HE)",
				from: "/impact/he",
				to: "https://www.instructure.com/higher-education/products/impact/?utm_source=INST&utm_medium=ER&CampaignID=7013m000001NyAxAAK",
				lang: "EN",
			},
			{
				title: "Home (K12)",
				from: "/impact/k12",
				to: "https://www.instructure.com/k12/products/impact/?utm_source=INST&utm_medium=ER&CampaignID=7013m000001NyAxAAK",
				lang: "EN",
			},
			{
				title: "Community",
				from: "/impact/community",
				to: "https://community.canvaslms.com/t5/Impact/ct-p/impact",
				lang: "EN",
			},
			{
				title: "Guides",
				from: "/impact/guides",
				to: "https://community.canvaslms.com/t5/Impact-Guides/tkb-p/impact_guides",
				lang: "EN",
			},
			{
				title: "Release Notes",
				from: "/impact/releases",
				to: "https://community.canvaslms.com/t5/Impact-Releases/ct-p/impact_releases",
				lang: "EN",
			},
		],
	},
	{
		brand: "LearnPlatform",
		links: [
			{
				title: "Home",
				from: "/learnplatform",
				to: "https://www.instructure.com/k12/products/learnplatform/?utm_source=INST&utm_medium=ER&CampaignID=7013m000001NyAxAAK",
				lang: "EN",
			},
			{
				title: "Compliance Package",
				from: "/learnplatform/dl",
				to: "https://github.com/thedannywahl/instructure-security-package/archive/refs/heads/learnplatform.zip",
				lang: "EN",
			},
			{
				title: "Terms of Service",
				from: "/learnplatform/tos",
				to: "https://www.instructure.com/policies/learnplatform-terms-of-service/?utm_source=INST&utm_medium=ER&CampaignID=7013m000001NyAxAAK",
				lang: "EN",
			},
			{
				title: "Privacy",
				from: "/learnplatform/privacy",
				to: "https://www.instructure.com/policies/privacy-learnplatform/?utm_source=INST&utm_medium=ER&CampaignID=7013m000001NyAxAAK",
				lang: "EN",
			},
			{
				title: "Data Processing Agreement",
				from: "/learnplatform/dpa",
				to: "https://www.instructure.com/policies/learnplatform-data-processing-agreement/?utm_source=INST&utm_medium=ER&CampaignID=7013m000001NyAxAAK",
				lang: "EN",
			},
			{
				title: "Statement of Neutrality",
				from: "/learnplatform/neutrality",
				to: "https://www.instructure.com/policies/learnplatform-neutrality/?utm_source=INST&utm_medium=ER&CampaignID=7013m000001NyAxAAK",
				lang: "EN",
			},
		],
	},
];

export default Links;
