const strings: PageStrings = {
  language: {
    EN: "Language",
    ES_LA: "Idioma",
    PT_BR: "Idioma",
    DE: "Sprache",
  },
  help: {
    EN: "Help",
    ES_LA: "Ayuda",
    PT_BR: "Ajuda",
    DE: "Hilfe",
  },
  toggle_menu: {
    EN: "Toggle menu",
    ES_LA: "Alternar menú",
    PT_BR: "Alternar menu",
    DE: "Menü umschalten",
  },
  main_menu: {
    EN: "Main menu",
    ES_LA: "Menú principal",
    PT_BR: "Menu principal",
    DE: "Hauptmenü",
  },
  page_navigation: {
    EN: "Page navigation",
    ES_LA: "Navegación de la página",
    PT_BR: "Navegação da página",
    DE: "Seitenavigation",
  },
  more: {
    EN: "More",
    ES_LA: "Más",
    PT_BR: "Mais",
    DE: "Mehr",
  },
  actions: {
    EN: "Actions",
    ES_LA: "Acciones",
    PT_BR: "Ações",
    DE: "Aktionen",
  },
  more_actions: {
    EN: "More actions",
    ES_LA: "Más acciones",
    PT_BR: "Mais ações",
    DE: "Mehr Aktionen",
  },
  contact_info: {
    EN: "Contact Information",
    ES_LA: "Información de Contacto",
    PT_BR: "Informações de Contato",
    DE: "Kontaktinformationen",
  },
  info_overview: {
    EN: "This site and its contents are maintained by Instructure, inc.",
    ES_LA: "Este sitio y su contenido son mantenidos por Instructure, inc.",
    PT_BR: "Este site e seu conteúdo são mantidos pela Instructure, inc.",
    DE: "Diese Website und ihre Inhalte werden von Instructure, inc. gepflegt.",
  },
  current_customers: {
    EN: "Current customers",
    ES_LA: "Clientes actuales",
    PT_BR: "Clientes atuais",
    DE: "Aktuelle kunden",
  },
  contact_csm: {
    EN: "Reach out to your CSM.",
    ES_LA: "Comuníquese con su CSM.",
    PT_BR: "Entre em contato com seu CSM.",
    DE: "Kontaktieren Sie Ihren CSM.",
  },
  prospects: {
    EN: "Prospective customers",
    ES_LA: "Clientes potenciales",
    PT_BR: "Clientes em potencial",
    DE: "Potenzielle Kunden",
  },
  contact_sales: {
    EN: "Reach out to your sales contact.",
    ES_LA: "Comuníquese con su contacto de ventas.",
    PT_BR: "Entre em contato com seu contato de vendas.",
    DE: "Kontaktieren Sie Ihren Vertriebskontakt.",
  },
  contact_general: {
    EN: "For general inquiries email",
    ES_LA: "Para consultas generales envíe un correo electrónico a",
    PT_BR: "Para perguntas gerais, envie um e-mail para",
    DE: "Für allgemeine Anfragen senden Sie eine E-Mail an",
  },
  redirects: {
    EN: "Redirects",
    ES_LA: "Redirecciones",
    PT_BR: "Redirecionamentos",
    DE: "Weiterleitungen",
  },
  releases: {
    EN: "Releases",
    ES_LA: "Lanzamientos",
    PT_BR: "Lançamentos",
    DE: "Veröffentlichungen",
  },
  contact: {
    EN: "Contact",
    ES_LA: "Contacto",
    PT_BR: "Contato",
    DE: "Kontakt",
  },
};
export default strings;
